use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "TrueShot API",
        version = "6.8.0",
        description = "Intelligent 3D scanning and photogrammetry API"
    ),
    servers(
        (url = "http://localhost:3000", description = "Local development")
    ),
    tags(
        (name = "general", description = "General service endpoints"),
        (name = "system", description = "System stats"),
        (name = "health", description = "Health and readiness"),
        (name = "audit", description = "Audit log access"),
        (name = "auth", description = "Authentication and sessions"),
        (name = "wizard", description = "Scan wizard endpoints"),
        (name = "scan", description = "Scan execution"),
        (name = "calibration", description = "Camera calibration"),
        (name = "hardware", description = "Camera/turntable control"),
        (name = "devices", description = "Unified device manager"),
        (name = "storage", description = "Storage providers"),
        (name = "project", description = "Project management"),
        (name = "edits", description = "Asset editing"),
        (name = "share", description = "Share links and embeds"),
        (name = "jobs", description = "Background job queue"),
        (name = "guest", description = "Guest portal events"),
        (name = "phones", description = "Slave phone control"),
        (name = "websocket", description = "Realtime websocket"),
        (name = "docs", description = "API documentation")
    ),
    paths(
        crate::api::docs::get_api_docs,
        crate::api::general::health_check,
        crate::api::general::get_logs,
        crate::api::general::export_logs,
        crate::api::system::get_system_stats,
        crate::api::health::health,
        crate::api::health::ready,
        crate::api::audit::get_audit,
        crate::api::auth::guest_token,
        crate::api::auth::bootstrap_status,
        crate::api::auth::bootstrap_admin,
        crate::api::auth::login,
        crate::api::auth::create_session,
        crate::api::auth::clear_session,
        crate::api::auth::refresh_session,
        crate::api::auth::logout_all,
        crate::api::auth::create_api_token,
        crate::api::auth::list_api_tokens,
        crate::api::auth::revoke_api_token,
        crate::api::auth::pairing_start,
        crate::api::auth::pairing_claim,
        crate::api::license::get_license_status,
        crate::api::license::get_license_bundles,
        crate::api::license::get_license_entitlements,
        crate::api::license::get_license_catalog,
        crate::api::license::get_license_tiers,
        crate::api::license::create_license_trial,
        crate::api::license::create_license_trial_self,
        crate::api::license::import_license,
        crate::api::license::get_license_devices,
        crate::api::license::activate_license_device,
        crate::api::license::deactivate_license_device,
        crate::api::project::get_projects,
        crate::api::project::get_projects_legacy,
        crate::api::project::create_project,
        crate::api::project::purge_project_raw,
        crate::api::project::open_project_fs,
        crate::api::project::import_model,
        crate::api::project::download_output_file,
        crate::api::project::list_project_assets,
        crate::api::project::download_processed_file,
        crate::api::project::download_raw_file,
        crate::api::project::get_imu_diagnostics,
        crate::api::project::get_project_license,
        crate::api::project::update_project_license,
        crate::api::project::encrypt_project,
        crate::api::project::decrypt_project,
        crate::api::annotations::get_project_annotations,
        crate::api::annotations::save_project_annotations,
        crate::api::edits::edit_mesh,
        crate::api::edits::edit_splat,
        crate::api::edits::get_edit_history,
        crate::api::share::create_share_link,
        crate::api::share::get_share_link,
        crate::api::share::get_share_asset,
        crate::api::share::get_share_analytics,
        crate::api::share::set_share_public,
        crate::api::share::get_share_public,
        crate::api::share::list_public_shares,
        crate::api::share::get_share_annotations,
        crate::api::scan::get_background_status,
        crate::api::scan::capture_background,
        crate::api::scan::get_detection_status,
        crate::api::scan::get_quality_status,
        crate::api::scan::get_quality_history,
        crate::api::scan::get_uncertainty_map,
        crate::api::scan::analyze_object,
        crate::api::scan::compute_scan_plan,
        crate::api::scan::start_scan,
        crate::api::scan::stop_scan,
        crate::api::scan::get_scan_progress,
        crate::api::scan::get_scan_coverage,
        crate::api::scan::execute_step,
        crate::api::scan::trigger_capture,
        crate::api::scan::get_sdcard_status,
        crate::api::scan::import_from_sdcard,
        crate::api::calibration::capture_calibration_frame,
        crate::api::calibration::compute_calibration,
        crate::api::calibration::compute_color_calibration,
        crate::api::calibration::clear_calibration_session,
        crate::api::calibration::clear_calibration_session_delete,
        crate::api::calibration::list_calibrations,
        crate::api::calibration::get_calibration,
        crate::api::jobs::submit_job,
        crate::api::jobs::list_jobs,
        crate::api::jobs::get_job,
        crate::api::hardware::get_cameras,
        crate::api::hardware::update_camera_nickname,
        crate::api::hardware::camera_ptz,
        crate::api::hardware::set_camera_config,
        crate::api::hardware::capture_photo,
        crate::api::hardware::capture_hdr_bracket,
        crate::api::hardware::capture_focus_stack,
        crate::api::hardware::capture_hdr_focus_stack,
        crate::api::hardware::set_camera_enabled,
        crate::api::hardware::start_intervalometer,
        crate::api::hardware::stop_intervalometer,
        crate::api::hardware::get_intervalometer_status,
        crate::api::hardware::camera_focus_point,
        crate::api::hardware::camera_autofocus,
        crate::api::hardware::camera_drive_focus,
        crate::api::hardware::camera_stream,
        crate::api::hardware::get_turntable_status,
        crate::api::hardware::turntable_home,
        crate::api::hardware::turntable_rotate,
        crate::api::hardware::scan_hardware,
        crate::api::devices::get_all_devices,
        crate::api::devices::get_device_stats,
        crate::api::devices::device_action,
        crate::api::devices::batch_device_action,
        crate::api::storage::list_providers,
        crate::api::storage::list_storage,
        crate::api::storage::get_storage,
        crate::api::storage::get_oauth_url,
        crate::api::storage::oauth_callback,
        crate::api::storage::add_storage,
        crate::api::storage::remove_storage,
        crate::api::storage::sync_storage,
        crate::api::storage::list_backup_jobs,
        crate::api::storage::get_backup_job,
        crate::api::storage::start_backup,
        crate::api::storage::restore_backup,
        crate::api::websocket::ws_index,
        crate::guest::list_events,
        crate::guest::create_event,
        crate::guest::get_event,
        crate::guest::update_event,
        crate::guest::delete_event,
        crate::guest::activate_event,
        crate::guest::guest_connect,
        crate::guest::list_guests,
        crate::guest::time_sync,
        crate::guest::start_all_recording,
        crate::guest::stop_all_recording,
        crate::guest::list_recordings,
        crate::guest::slave::list_phones,
        crate::guest::slave::get_phone,
        crate::guest::slave::capture_phone,
        crate::guest::slave::capture_all_phones,
        crate::guest::slave::set_phone_resolution,
        crate::guest::slave::get_capture_results,
        crate::guest::slave::phone_websocket
    )
)]
pub struct ApiDoc;
