from .index import index
from .models import models
from .settings import settings
from .about import about
from .profile import profile
from .login import login
from .signup import signup
from .machines import machines
from .devices import devices
from .implementationManager import implementationManager
from .jobManager import jobManager
from .forgotPassword import forgotPassword
from .modelViewer import modelViewer
from .photoAcquisition import photoAcquisition
from .selectCurrentMachine import selectCurrentMachine
