"""Added notes to model

Revision ID: 686c2cc5fa99
Revises: efdf880e275b
Create Date: 2024-08-27 12:47:01.006235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '686c2cc5fa99'
down_revision: Union[str, None] = 'efdf880e275b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meshmodel', sa.Column('notes', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meshmodel', 'notes')
    # ### end Alembic commands ###
