"""change hdr step size to string

Revision ID: 7314c7fc6c8d
Revises: 96af2e7c6273
Create Date: 2024-10-13 19:36:51.853567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7314c7fc6c8d'
down_revision: Union[str, None] = '96af2e7c6273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photosequence', 'hdr_step_size')
    op.add_column('photosequence', sa.Column('hdr_step_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
