"""Adding more HDR fields

Revision ID: 96af2e7c6273
Revises: 686c2cc5fa99
Create Date: 2024-10-13 18:25:25.846783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96af2e7c6273'
down_revision: Union[str, None] = '686c2cc5fa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photosequence', sa.Column('hdr_starting_shutter_speed', sqlmodel.sql.sqltypes.AutoString(),  nullable=False, server_default='1/100'))
    op.add_column('photosequence', sa.Column('hdr_step_size', sa.Float(), nullable=False, server_default='1.0'))
    op.alter_column('photosequence', 'hdr_starting_shutter_speed', server_default=None)
    op.alter_column('photosequence', 'hdr_step_size', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photosequence', 'hdr_step_size')
    op.drop_column('photosequence', 'hdr_starting_shutter_speed')
    # ### end Alembic commands ###
