"""editing table definitions

Revision ID: a1192f15843a
Revises: 4cef3906712e
Create Date: 2025-02-19 22:58:31.103928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1192f15843a'
down_revision: Union[str, None] = '4cef3906712e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('machine_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'device', 'machine', ['machine_id'], ['id'])
    op.add_column('job', sa.Column('machine_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'job', 'machine', ['machine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'machine_id')
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.drop_column('device', 'machine_id')
    # ### end Alembic commands ###
