"""initial migration

Revision ID: efdf880e275b
Revises: 
Create Date: 2024-08-25 19:43:07.899157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'efdf880e275b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camerapreset',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aperture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shutter_speed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exposure_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exposure_compensation', sa.Integer(), nullable=False),
    sa.Column('white_balance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meshmodel',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photosequence',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('camera_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aperture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shutter_speed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exposure_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('camera_preset_id', sa.Uuid(), nullable=True),
    sa.Column('hdr', sa.Boolean(), nullable=False),
    sa.Column('hdr_exposures', sa.Integer(), nullable=False),
    sa.Column('focus_stacking', sa.Boolean(), nullable=False),
    sa.Column('focus_steps', sa.Integer(), nullable=False),
    sa.Column('focus_step_width', sa.Integer(), nullable=False),
    sa.Column('mesh_model_id', sa.Uuid(), nullable=True),
    sa.Column('rotation_total', sa.Integer(), nullable=False),
    sa.Column('rotation_step', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_turntable_step', sa.Integer(), nullable=False),
    sa.Column('turntable_steps_remaining', sa.Integer(), nullable=False),
    sa.Column('photos_taken', sa.Integer(), nullable=False),
    sa.Column('photos_remaining', sa.Integer(), nullable=False),
    sa.Column('photos_per_minutes', sa.Float(), nullable=False),
    sa.Column('time_elapsed', sa.Integer(), nullable=False),
    sa.Column('time_remaining', sa.Integer(), nullable=False),
    sa.Column('percennt_complete', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photos_start', sa.DateTime(), nullable=True),
    sa.Column('photos_finish', sa.DateTime(), nullable=True),
    sa.Column('photos_completed', sa.Boolean(), nullable=False),
    sa.Column('transfer_start', sa.DateTime(), nullable=True),
    sa.Column('transfer_finish', sa.DateTime(), nullable=True),
    sa.Column('transfer_completed', sa.Boolean(), nullable=False),
    sa.Column('focus_start', sa.DateTime(), nullable=True),
    sa.Column('focus_finish', sa.DateTime(), nullable=True),
    sa.Column('focus_completed', sa.Boolean(), nullable=False),
    sa.Column('hdr_start', sa.DateTime(), nullable=True),
    sa.Column('hdr_finish', sa.DateTime(), nullable=True),
    sa.Column('hdr_completed', sa.Boolean(), nullable=False),
    sa.Column('background_start', sa.DateTime(), nullable=True),
    sa.Column('background_finish', sa.DateTime(), nullable=True),
    sa.Column('background_removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_preset_id'], ['camerapreset.id'], ),
    sa.ForeignKeyConstraint(['mesh_model_id'], ['meshmodel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photosequence')
    op.drop_table('meshmodel')
    op.drop_table('camerapreset')
    # ### end Alembic commands ###
